In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import os

In [13]:
# Loads the dataset into memory. Takes ~45 seconds to load the dataset.
df = pd.read_csv('./data/Syn.csv')
# df = pd.read_csv('./data/data-primary/unbalaced_20_80_dataset.csv')

/tmp/ipykernel_17206/3996427861.py:2: DtypeWarning: Columns (85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/Syn.csv')

In [14]:
df.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,445444,172.16.0.5-192.168.50.4-9429-9429-6,172.16.0.5,9429,192.168.50.4,9429,6,2018-11-03 11:36:28.607338,36063894,7,...,29.444864,52.0,1.0,1.202128e+07,6.253623e+06,18628035.0,6193840.0,0,1,Syn
1,113842,172.16.0.5-192.168.50.4-60224-60224-6,172.16.0.5,60224,192.168.50.4,60224,6,2018-11-03 11:36:28.607339,44851366,8,...,0.000000,1.0,1.0,2.066268e+07,1.169783e+07,28934293.0,12391060.0,0,1,Syn
2,176377,172.16.0.5-192.168.50.4-33827-11746-6,192.168.50.4,11746,172.16.0.5,33827,6,2018-11-03 11:36:28.607388,1,2,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,0,Syn
3,24777,172.16.0.5-192.168.50.4-33828-1431-6,172.16.0.5,33828,192.168.50.4,1431,6,2018-11-03 11:36:28.607391,0,2,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,1,Syn
4,85100,172.16.0.5-192.168.50.4-5311-5311-6,172.16.0.5,5311,192.168.50.4,5311,6,2018-11-03 11:36:28.607442,35731470,8,...,33.234019,48.0,1.0,1.191047e+07,1.849493e+06,13693985.0,10001398.0,0,1,Syn

In [10]:
temp = df[['Flow ID', 'Src IP', 'Dst IP', 'Src Port', 'Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'CWE Flag Count', 'ECE Flag Cnt']]

In [11]:
temp.head()

,Flow ID,Src IP,Dst IP,Src Port,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,SYN Flag Cnt,RST Flag Cnt,PSH Flag Cnt,ACK Flag Cnt,URG Flag Cnt,CWE Flag Count,ECE Flag Cnt
0,172.31.69.25-18.219.193.20-80-37882-6,18.219.193.20,172.31.69.25,37882,80,6,16/02/2018 11:27:29 PM,8660,1,0,0,0,1,0,0,0
1,172.31.69.28-18.219.9.1-80-63287-6,172.31.69.28,18.219.9.1,80,63287,6,22/02/2018 12:13:52 AM,5829,4,1,0,0,0,0,1,1
2,172.31.69.28-52.14.136.135-80-63095-6,52.14.136.135,172.31.69.28,63095,80,6,22/02/2018 12:14:02 AM,3396,1,0,0,0,1,0,0,0
3,172.31.69.28-18.216.200.189-80-52341-6,18.216.200.189,172.31.69.28,52341,80,6,22/02/2018 12:28:04 AM,2390,1,0,0,0,1,0,0,0
4,172.31.69.28-18.218.55.126-80-57459-6,172.31.69.28,18.218.55.126,80,57459,6,22/02/2018 12:19:45 AM,17362,4,1,0,0,0,0,1,1